name: statuses
description: List of statuses referring to the state of an app.
version: 1.0.0
repository: https://github.com/dwyl/statuses

environment:
  sdk: '>=2.19.2 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
